config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("core.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("__reload__/", include("django_browser_reload.urls")),
    path("party/", include("core.party.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

core/party/urls.py
from django.urls import path

from . import views

app_name = "party"

list_parties_urlpatterns = [
    path("", views.PartyListPage.as_view(), name="page_party_list"),
]

party_detail_urlpatterns = [
    path("<uuid:party_uuid>/", views.PartyDetailPage.as_view(), name="page_single_party"),
    path("<uuid:party_uuid>/details/", views.PartyDetailPartial.as_view(), name="partial_party_detail"),
]

new_party_urlpatterns = [
    path("new/", views.page_new_party, name="page_new_party"),
    path("new/check-date/", views.partial_check_party_date, name="partial_check_party_date"),
    path("new/check-invitation/", views.partial_check_invitation, name="partial_check_invitation"),
]

gift_registry_urlpatterns = [
    path("<uuid:party_uuid>/gifts/", views.GiftRegistryPage.as_view(), name="page_gift_registry"),
    path("gifts/<uuid:gift_uuid>/", views.GiftDetailPartial.as_view(), name="partial_gift_detail"),
    path("gifts/<uuid:gift_uuid>/form/", views.GiftUpdateFormPartial.as_view(), name="partial_gift_update"),
    path("gifts/<uuid:gift_uuid>/delete/", views.delete_gift_partial, name="partial_gift_delete"),
    path("<uuid:party_uuid>/new-gift/", views.GiftCreateFormPartial.as_view(), name="partial_new_gift"),
]

guest_list_urlpatterns = [
    path("<uuid:party_uuid>/guests/", views.GuestListPage.as_view(), name="page_guest_list"),
    path("<uuid:party_uuid>/guests/mark-attending/", views.mark_attending_partial, name="partial_mark_attending"),
    path(
        "<uuid:party_uuid>/guests/mark-not-attending/",
        views.mark_not_attending_partial,
        name="partial_mark_not_attending",
    ),
    path("party/<uuid:party_uuid>/guests/filter/", views.filter_guests_partial, name="partial_filter_guests"),
]


urlpatterns = (
    list_parties_urlpatterns
    + party_detail_urlpatterns
    + new_party_urlpatterns
    + gift_registry_urlpatterns
    + guest_list_urlpatterns
)

core/users/urls.py
from django.urls import path

from core.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

core/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

core/party/views/gift_registry_views.py
from django.http import QueryDict
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.decorators.http import require_http_methods
from django.views.generic import DetailView, ListView

from core.party.forms import GiftForm
from core.party.models import Gift, Party


class GiftRegistryPage(ListView):
    model = Gift
    template_name = "party/gift_registry/page_gift_registry.html"
    context_object_name = "gifts"

    def get_queryset(self):
        return Gift.objects.filter(party_id=self.kwargs["party_uuid"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["party"] = Party.objects.get(uuid=self.kwargs["party_uuid"])
        return context


class GiftDetailPartial(DetailView):
    model = Gift
    template_name = "party/gift_registry/partial_gift_detail.html"
    context_object_name = "gift"
    pk_url_kwarg = "gift_uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["party"] = self.object.party
        return context


class GiftUpdateFormPartial(View):
    def get(self, request, gift_uuid, *args, **kwargs):
        gift = get_object_or_404(Gift, uuid=gift_uuid)
        form = GiftForm(instance=gift)

        return render(
            request,
            "party/gift_registry/partial_gift_update.html",
            {"form": form, "gift": gift},
        )

    def put(self, request, gift_uuid, *args, **kwargs):
        data = QueryDict(request.body).dict()
        gift = Gift.objects.get(uuid=gift_uuid)
        form = GiftForm(data, instance=gift)

        if form.is_valid():
            form.save()

            return render(request, "party/gift_registry/partial_gift_detail.html", {"gift": gift, "party": gift.party})

        return render(request, "party/gift_registry/partial_gift_update.html", {"form": form, "gift": gift})


@require_http_methods(["DELETE"])
def delete_gift_partial(request, gift_uuid):
    gift = get_object_or_404(Gift, uuid=gift_uuid)
    gift.delete()

    return render(request, "party/gift_registry/partial_gift_removed.html")


class GiftCreateFormPartial(View):
    def get(self, request, party_uuid, *args, **kwargs):
        form = GiftForm()

        return render(request, "party/gift_registry/partial_gift_new.html", {"form": form, "party_id": party_uuid})

    def post(self, request, party_uuid, *args, **kwargs):
        party = get_object_or_404(Party, uuid=party_uuid)
        form = GiftForm(request.POST)

        if form.is_valid():
            gift = form.save(commit=False)
            gift.party = party
            gift.save()

            return render(request, "party/gift_registry/partial_gift_detail.html", {"gift": gift, "party": party})

        return render(request, "party/gift_registry/partial_gift_new.html", {"form": form, "party_id": party_uuid})

core/party/views/guest_list_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import QueryDict
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from core.party.models import Guest


class GuestListPage(LoginRequiredMixin, ListView):
    model = Guest
    template_name = "party/guest_list/page_guest_list.html"
    context_object_name = "guests"

    def get_queryset(self):
        return Guest.objects.filter(party_id=self.kwargs["party_uuid"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["party_id"] = self.kwargs["party_uuid"]
        context["attending_num"] = self.object_list.filter(attending=True).count()

        return context


@login_required
@require_http_methods(["PUT"])
def mark_attending_partial(request, party_uuid):
    mark_attending = QueryDict(request.body).getlist("guest_ids")
    Guest.objects.filter(uuid__in=mark_attending).update(attending=True)

    guests = Guest.objects.filter(party_id=party_uuid)

    return render(
        request,
        "party/guest_list/partial_guest_list.html",
        {"guests": guests},
    )


@login_required
@require_http_methods(["PUT"])
def mark_not_attending_partial(request, party_uuid):
    mark_not_attending = QueryDict(request.body).getlist("guest_ids")
    Guest.objects.filter(uuid__in=mark_not_attending).update(attending=False)

    guests = Guest.objects.filter(party_id=party_uuid)

    return render(
        request,
        "party/guest_list/partial_guest_list.html",
        {"guests": guests},
    )


def filter_attending(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id, attending=True)


def filter_not_attending(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id, attending=False)


def filter_attending_and_search(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id, attending=True, name__icontains=kwargs["search_text"])


def filter_not_attending_and_search(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id, attending=False, name__icontains=kwargs["search_text"])


def filter_search(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id, name__icontains=kwargs["search_text"])


def filter_default(party_id, **kwargs):
    return Guest.objects.filter(party_id=party_id)


QUERY_FILTERS = {
    ("attending", False): filter_attending,
    ("not_attending", False): filter_not_attending,
    ("attending", True): filter_attending_and_search,
    ("not_attending", True): filter_not_attending_and_search,
    ("all", True): filter_search,
}


@require_http_methods(["POST"])
def filter_guests_partial(request, party_uuid):
    attending_filter = request.POST.get("attending_filter")
    search_text = request.POST.get("guest_search")

    query_filter = QUERY_FILTERS.get((attending_filter, bool(search_text)), filter_default)

    guests = query_filter(party_id=party_uuid, search_text=search_text)

    return render(request, "party/guest_list/partial_guest_list.html", {"guests": guests})

core/party/views/new_party_views.py
from crispy_forms.templatetags.crispy_forms_filters import as_crispy_field
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render

from core.party.forms import PartyForm


@login_required
def page_new_party(request):
    form = PartyForm()

    if request.method == "POST":
        form = PartyForm(request.POST)
        if form.is_valid():
            party = form.save(commit=False)
            party.organizer = request.user
            party.save()
            return redirect("party:page_single_party", party_uuid=party.uuid)

    return render(request, "party/new_party/page_new_party.html", {"form": form})


@login_required
def partial_check_party_date(request):
    form = PartyForm(request.GET)

    return HttpResponse(as_crispy_field(form["party_date"]))


@login_required
def partial_check_invitation(request):
    form = PartyForm(request.GET)

    return HttpResponse(as_crispy_field(form["invitation"]))

core/party/views/party_detail_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import QueryDict
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.views.generic import DetailView

from core.party.forms import PartyForm
from core.party.models import Party


class PartyDetailPage(LoginRequiredMixin, DetailView):
    model = Party
    template_name = "party/party_detail/page_party_detail.html"
    pk_url_kwarg = "party_uuid"
    context_object_name = "party"


class PartyDetailPartial(LoginRequiredMixin, View):
    def get(self, request, party_uuid, *args, **kwargs):
        party = get_object_or_404(Party, uuid=party_uuid)
        form = PartyForm(instance=party)

        return render(
            request,
            "party/party_detail/partial_party_edit_form.html",
            {"party": party, "form": form},
        )

    def put(self, request, party_uuid, *args, **kwargs):
        party = get_object_or_404(Party, uuid=party_uuid)
        data = QueryDict(request.body).dict()
        form = PartyForm(data, instance=party)

        if form.is_valid():
            form.save()

        return render(
            request,
            "party/party_detail/partial_party_detail.html",
            {"party": party},
        )

core/party/views/party_list_views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from core.party.models import Party


class PartyListPage(LoginRequiredMixin, ListView):
    template_name = "party/party_list/page_parties_list.html"
    context_object_name = "parties"
    paginate_by = 6

    def get_queryset(self):
        return Party.objects.filter(
            organizer=self.request.user,
            party_date__gte=datetime.date.today(),
        ).order_by("party_date")

    def get_template_names(self):
        if "hx-request" in self.request.headers:
            return ["party/party_list/partial_parties_list.html"]
        else:
            return ["party/party_list/page_parties_list.html"]

core/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

core/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

core/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

core/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Party Tracker
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Django HTMX Alpine.js Tailwind" />
    <meta name="author" content="Antonio Vilchez Monge" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
            integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
      <!-- Your stuff: Third-Party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer
              src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
              integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-Party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Party Tracker</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'party:page_party_list' %}">Parties <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>